local M = {}

---@param c table color palette
---@return table
function M.get(c)
  return {
    -- nvim-cmp
    CmpItemAbbrMatch = { fg = c.accent, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.accent, bold = true },
    CmpItemKindFunction = { fg = c.func },
    CmpItemKindMethod = { fg = c.func },
    CmpItemKindVariable = { fg = c.variable },
    CmpItemKindKeyword = { fg = c.keyword },
    CmpItemKindText = { fg = c.fg },
    CmpItemKindProperty = { fg = c.property },
    CmpItemKindUnit = { fg = c.constant },
    CmpItemKindSnippet = { fg = c.accent },
    CmpItemKindClass = { fg = c.type },
    CmpItemKindInterface = { fg = c.type },
    CmpItemKindModule = { fg = c.keyword },
    CmpItemKindField = { fg = c.property },
    CmpItemKindConstant = { fg = c.constant },
    CmpItemKindEnum = { fg = c.enum },
    CmpItemKindEnumMember = { fg = c.constant },
    CmpItemKindStruct = { fg = c.type },
    CmpItemKindEvent = { fg = c.accent },
    CmpItemKindOperator = { fg = c.operator },
    CmpItemKindTypeParameter = { fg = c.type },
    CmpItemKindFile = { fg = c.fg },
    CmpItemKindFolder = { fg = c.accent },
    CmpItemKindReference = { fg = c.accent },

    -- blink.cmp
    BlinkCmpMenu = { fg = c.fg, bg = c.bg_dark },
    BlinkCmpMenuBorder = { fg = c.border, bg = c.bg_dark },
    BlinkCmpMenuSelection = { bg = c.bg_visual },
    BlinkCmpLabel = { fg = c.fg },
    BlinkCmpLabelDeprecated = { fg = c.fg_dark, strikethrough = true },
    BlinkCmpLabelMatch = { fg = c.accent, bold = true },
    BlinkCmpKind = { fg = c.accent },
    BlinkCmpKindClass = { fg = c.type },
    BlinkCmpKindColor = { fg = c.accent },
    BlinkCmpKindConstant = { fg = c.constant },
    BlinkCmpKindConstructor = { fg = c.func },
    BlinkCmpKindEnum = { fg = c.enum },
    BlinkCmpKindEnumMember = { fg = c.constant },
    BlinkCmpKindEvent = { fg = c.accent },
    BlinkCmpKindField = { fg = c.property },
    BlinkCmpKindFile = { fg = c.fg },
    BlinkCmpKindFolder = { fg = c.accent },
    BlinkCmpKindFunction = { fg = c.func },
    BlinkCmpKindInterface = { fg = c.type },
    BlinkCmpKindKeyword = { fg = c.keyword },
    BlinkCmpKindMethod = { fg = c.func },
    BlinkCmpKindModule = { fg = c.keyword },
    BlinkCmpKindOperator = { fg = c.operator },
    BlinkCmpKindProperty = { fg = c.property },
    BlinkCmpKindReference = { fg = c.accent },
    BlinkCmpKindSnippet = { fg = c.accent },
    BlinkCmpKindStruct = { fg = c.type },
    BlinkCmpKindText = { fg = c.fg },
    BlinkCmpKindTypeParameter = { fg = c.type },
    BlinkCmpKindUnit = { fg = c.constant },
    BlinkCmpKindValue = { fg = c.constant },
    BlinkCmpKindVariable = { fg = c.variable },
    BlinkCmpDoc = { fg = c.fg, bg = c.bg_dark },
    BlinkCmpDocBorder = { fg = c.border, bg = c.bg_dark },
    BlinkCmpSignatureHelp = { fg = c.fg, bg = c.bg_dark },
    BlinkCmpSignatureHelpBorder = { fg = c.border, bg = c.bg_dark },
    BlinkCmpGhostText = { fg = c.fg_muted },
  }
end

return M
