local M = {}

---@param c table color palette
---@return table
function M.get(c)
  return {
    -- Treesitter
    ['@attribute'] = { fg = c.attribute },
    ['@boolean'] = { fg = c.boolean },
    ['@character'] = { fg = c.string },
    ['@character.special'] = { fg = c.string },
    ['@comment'] = { fg = c.comment, italic = true },
    ['@conditional'] = { link = '@keyword.conditional' },
    ['@constant'] = { fg = c.constant },
    ['@constant.builtin'] = { fg = c.constant },
    ['@constant.macro'] = { fg = c.constant },
    ['@constructor'] = { fg = c.func },
    ['@exception'] = { link = '@keyword.exception' },
    ['@field'] = { link = '@variable.member' },
    ['@float'] = { link = '@number.float' },
    ['@function'] = { fg = c.func },
    ['@function.builtin'] = { fg = c.func },
    ['@function.call'] = { fg = c.func },
    ['@function.macro'] = { fg = c.func },
    ['@function.method'] = { fg = c.func },
    ['@function.method.call'] = { fg = c.func },
    ['@include'] = { link = '@keyword.import' },
    ['@keyword'] = { fg = c.keyword },
    ['@keyword.conditional'] = { fg = c.keyword },
    ['@keyword.exception'] = { fg = c.keyword },
    ['@keyword.function'] = { fg = c.keyword },
    ['@keyword.import'] = { fg = c.keyword },
    ['@keyword.operator'] = { fg = c.operator },
    ['@keyword.repeat'] = { fg = c.keyword },
    ['@keyword.return'] = { fg = c.keyword },
    ['@label'] = { fg = c.keyword },
    ['@markup'] = { fg = c.fg },
    ['@markup.heading'] = { fg = c.accent, bold = true },
    ['@markup.italic'] = { italic = true },
    ['@markup.link'] = { fg = c.accent },
    ['@markup.link.url'] = { fg = c.accent, underline = true },
    ['@markup.raw'] = { fg = c.string },
    ['@markup.strong'] = { bold = true },
    ['@markup.underline'] = { underline = true },
    ['@method'] = { link = '@function.method' },
    ['@method.call'] = { link = '@function.method.call' },
    ['@module'] = { fg = c.fg },
    ['@namespace'] = { link = '@module' },
    ['@number'] = { fg = c.number },
    ['@number.float'] = { fg = c.number },
    ['@operator'] = { fg = c.operator },
    ['@parameter'] = { link = '@variable.parameter' },
    ['@property'] = { link = '@variable.member' },
    ['@punctuation.bracket'] = { fg = c.fg },
    ['@punctuation.delimiter'] = { fg = c.fg },
    ['@punctuation.special'] = { fg = c.accent },
    ['@repeat'] = { link = '@keyword.repeat' },
    ['@string'] = { fg = c.string },
    ['@string.escape'] = { fg = c.fg_muted },
    ['@string.regex'] = { fg = c.string },
    ['@string.special'] = { fg = c.string },
    ['@tag'] = { fg = c.tag },
    ['@tag.attribute'] = { fg = c.attribute },
    ['@tag.delimiter'] = { fg = c.fg },
    ['@text'] = { link = '@markup' },
    ['@text.danger'] = { fg = c.error },
    ['@text.emphasis'] = { link = '@markup.italic' },
    ['@text.literal'] = { link = '@markup.raw' },
    ['@text.reference'] = { link = '@markup.link' },
    ['@text.strong'] = { link = '@markup.strong' },
    ['@text.title'] = { link = '@markup.heading' },
    ['@text.todo'] = { fg = c.accent, bold = true },
    ['@text.underline'] = { link = '@markup.underline' },
    ['@text.uri'] = { link = '@markup.link.url' },
    ['@text.warning'] = { fg = c.warning },
    ['@type'] = { fg = c.type },
    ['@type.builtin'] = { fg = c.type },
    ['@type.definition'] = { fg = c.type },
    ['@type.qualifier'] = { fg = c.keyword },
    ['@variable'] = { fg = c.variable },
    ['@variable.builtin'] = { fg = c.variable_special },
    ['@variable.member'] = { fg = c.property },
    ['@variable.parameter'] = { fg = c.variable },
  }
end

return M
