local M = {}

---@param c table color palette
---@return table
function M.get(c)
  return {
    -- Treesitter
    ["@attribute"] = { fg = c.attribute },
    ["@boolean"] = { fg = c.boolean },
    ["@character"] = { fg = c.string },
    ["@comment"] = { fg = c.comment, italic = true },
    ["@conditional"] = { fg = c.keyword },
    ["@constant"] = { fg = c.constant },
    ["@constant.builtin"] = { fg = c.constant },
    ["@constant.macro"] = { fg = c.constant },
    ["@constructor"] = { fg = c.func },
    ["@exception"] = { fg = c.keyword },
    ["@field"] = { fg = c.property },
    ["@float"] = { fg = c.number },
    ["@function"] = { fg = c.func },
    ["@function.builtin"] = { fg = c.func },
    ["@function.call"] = { fg = c.func },
    ["@function.macro"] = { fg = c.func },
    ["@include"] = { fg = c.keyword },
    ["@keyword"] = { fg = c.keyword },
    ["@keyword.function"] = { fg = c.keyword },
    ["@keyword.operator"] = { fg = c.operator },
    ["@keyword.return"] = { fg = c.keyword },
    ["@label"] = { fg = c.keyword },
    ["@method"] = { fg = c.func },
    ["@method.call"] = { fg = c.func },
    ["@namespace"] = { fg = c.fg },
    ["@number"] = { fg = c.number },
    ["@operator"] = { fg = c.operator },
    ["@parameter"] = { fg = c.variable },
    ["@property"] = { fg = c.property },
    ["@punctuation.bracket"] = { fg = c.fg },
    ["@punctuation.delimiter"] = { fg = c.fg },
    ["@punctuation.special"] = { fg = c.accent },
    ["@repeat"] = { fg = c.keyword },
    ["@string"] = { fg = c.string },
    ["@string.escape"] = { fg = c.fg_muted },
    ["@string.regex"] = { fg = c.string },
    ["@string.special"] = { fg = c.string },
    ["@tag"] = { fg = c.tag },
    ["@tag.attribute"] = { fg = c.attribute },
    ["@tag.delimiter"] = { fg = c.fg },
    ["@text"] = { fg = c.fg },
    ["@text.danger"] = { fg = c.error },
    ["@text.emphasis"] = { italic = true },
    ["@text.literal"] = { fg = c.string },
    ["@text.reference"] = { fg = c.accent },
    ["@text.strong"] = { bold = true },
    ["@text.title"] = { fg = c.accent, bold = true },
    ["@text.todo"] = { fg = c.accent, bold = true },
    ["@text.underline"] = { underline = true },
    ["@text.uri"] = { fg = c.accent, underline = true },
    ["@text.warning"] = { fg = c.warning },
    ["@type"] = { fg = c.type },
    ["@type.builtin"] = { fg = c.type },
    ["@type.definition"] = { fg = c.type },
    ["@type.qualifier"] = { fg = c.keyword },
    ["@variable"] = { fg = c.variable },
    ["@variable.builtin"] = { fg = c.variable_special },
  }
end

return M
